# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designUiFiles/addTaskDlg.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addTaskDlg(object):
    def setupUi(self, addTaskDlg):
        addTaskDlg.setObjectName("addTaskDlg")
        addTaskDlg.resize(477, 423)
        addTaskDlg.setMinimumSize(QtCore.QSize(477, 423))
        addTaskDlg.setMaximumSize(QtCore.QSize(477, 423))
        self.gridLayout = QtWidgets.QGridLayout(addTaskDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(addTaskDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(addTaskDlg)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(addTaskDlg)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.closeButton = QtWidgets.QPushButton(addTaskDlg)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 11, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(addTaskDlg)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(addTaskDlg)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 11, 1, 1, 1)
        self.fontSetting = QtWidgets.QCheckBox(addTaskDlg)
        self.fontSetting.setObjectName("fontSetting")
        self.gridLayout.addWidget(self.fontSetting, 9, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 3, 1)
        self.label_7 = QtWidgets.QLabel(addTaskDlg)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 8, 0, 1, 1)
        self.durationEntry = QtWidgets.QSpinBox(addTaskDlg)
        self.durationEntry.setWrapping(True)
        self.durationEntry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.durationEntry.setAccelerated(True)
        self.durationEntry.setMinimum(1)
        self.durationEntry.setMaximum(1440)
        self.durationEntry.setProperty("value", 5)
        self.durationEntry.setObjectName("durationEntry")
        self.gridLayout.addWidget(self.durationEntry, 1, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(addTaskDlg)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(addTaskDlg)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.noDurationButton = QtWidgets.QPushButton(addTaskDlg)
        self.noDurationButton.setCheckable(True)
        self.noDurationButton.setObjectName("noDurationButton")
        self.gridLayout.addWidget(self.noDurationButton, 1, 4, 1, 1)
        self.taskEntry = QtWidgets.QComboBox(addTaskDlg)
        self.taskEntry.setEditable(True)
        self.taskEntry.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.taskEntry.setObjectName("taskEntry")
        self.gridLayout.addWidget(self.taskEntry, 0, 1, 1, 4)
        self.fontName = QtWidgets.QFontComboBox(addTaskDlg)
        self.fontName.setObjectName("fontName")
        self.gridLayout.addWidget(self.fontName, 3, 1, 1, 4)
        self.dateEntry = QtWidgets.QDateEdit(addTaskDlg)
        self.dateEntry.setCalendarPopup(True)
        self.dateEntry.setObjectName("dateEntry")
        self.gridLayout.addWidget(self.dateEntry, 2, 1, 1, 4)
        self.fontSize = QtWidgets.QSpinBox(addTaskDlg)
        self.fontSize.setWrapping(True)
        self.fontSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.fontSize.setPrefix("")
        self.fontSize.setMinimum(10)
        self.fontSize.setMaximum(100)
        self.fontSize.setSingleStep(2)
        self.fontSize.setProperty("value", 10)
        self.fontSize.setObjectName("fontSize")
        self.gridLayout.addWidget(self.fontSize, 4, 1, 1, 4)
        self.fontStyle = QtWidgets.QComboBox(addTaskDlg)
        self.fontStyle.setObjectName("fontStyle")
        self.fontStyle.addItem("")
        self.fontStyle.addItem("")
        self.fontStyle.addItem("")
        self.gridLayout.addWidget(self.fontStyle, 5, 1, 1, 4)
        self.fontWeight = QtWidgets.QComboBox(addTaskDlg)
        self.fontWeight.setObjectName("fontWeight")
        self.fontWeight.addItem("")
        self.fontWeight.addItem("")
        self.gridLayout.addWidget(self.fontWeight, 6, 1, 1, 4)
        self.previewText = QtWidgets.QTextEdit(addTaskDlg)
        self.previewText.setReadOnly(True)
        self.previewText.setObjectName("previewText")
        self.gridLayout.addWidget(self.previewText, 7, 1, 2, 4)
        self.addTaskButton = QtWidgets.QPushButton(addTaskDlg)
        self.addTaskButton.setDefault(True)
        self.addTaskButton.setFlat(False)
        self.addTaskButton.setObjectName("addTaskButton")
        self.gridLayout.addWidget(self.addTaskButton, 11, 4, 1, 1)

        self.retranslateUi(addTaskDlg)
        self.closeButton.clicked.connect(addTaskDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(addTaskDlg)
        addTaskDlg.setTabOrder(self.taskEntry, self.durationEntry)
        addTaskDlg.setTabOrder(self.durationEntry, self.noDurationButton)
        addTaskDlg.setTabOrder(self.noDurationButton, self.dateEntry)
        addTaskDlg.setTabOrder(self.dateEntry, self.fontName)
        addTaskDlg.setTabOrder(self.fontName, self.fontSize)
        addTaskDlg.setTabOrder(self.fontSize, self.fontStyle)
        addTaskDlg.setTabOrder(self.fontStyle, self.fontWeight)
        addTaskDlg.setTabOrder(self.fontWeight, self.previewText)
        addTaskDlg.setTabOrder(self.previewText, self.fontSetting)
        addTaskDlg.setTabOrder(self.fontSetting, self.addTaskButton)
        addTaskDlg.setTabOrder(self.addTaskButton, self.closeButton)

    def retranslateUi(self, addTaskDlg):
        _translate = QtCore.QCoreApplication.translate
        addTaskDlg.setWindowTitle(_translate("addTaskDlg", "Add new task"))
        self.label_2.setText(_translate("addTaskDlg", "Day"))
        self.label_4.setText(_translate("addTaskDlg", "Font"))
        self.label.setText(_translate("addTaskDlg", "Task"))
        self.closeButton.setText(_translate("addTaskDlg", "&Close"))
        self.label_5.setText(_translate("addTaskDlg", "Font Size"))
        self.label_6.setText(_translate("addTaskDlg", "Font Style"))
        self.fontSetting.setText(_translate("addTaskDlg", "Remember last font settings."))
        self.label_7.setText(_translate("addTaskDlg", "Font Weight"))
        self.durationEntry.setSuffix(_translate("addTaskDlg", " Minutes"))
        self.label_3.setText(_translate("addTaskDlg", "Duration"))
        self.label_8.setText(_translate("addTaskDlg", "Preview"))
        self.noDurationButton.setText(_translate("addTaskDlg", "No Duration"))
        self.dateEntry.setDisplayFormat(_translate("addTaskDlg", "ddd MMMM dd yyyy"))
        self.fontSize.setSuffix(_translate("addTaskDlg", " pt"))
        self.fontStyle.setItemText(0, _translate("addTaskDlg", "Normal"))
        self.fontStyle.setItemText(1, _translate("addTaskDlg", "Italic"))
        self.fontStyle.setItemText(2, _translate("addTaskDlg", "Oblique"))
        self.fontWeight.setItemText(0, _translate("addTaskDlg", "Normal"))
        self.fontWeight.setItemText(1, _translate("addTaskDlg", "Bold"))
        self.addTaskButton.setText(_translate("addTaskDlg", "&Add"))

