# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designUiFiles/preferencesDlg.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_preferencesDlg(object):
    def setupUi(self, preferencesDlg):
        preferencesDlg.setObjectName("preferencesDlg")
        preferencesDlg.resize(717, 823)
        self.gridLayout = QtWidgets.QGridLayout(preferencesDlg)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 2, 1, 1)
        self.acceptButton = QtWidgets.QPushButton(preferencesDlg)
        self.acceptButton.setDefault(True)
        self.acceptButton.setObjectName("acceptButton")
        self.gridLayout.addWidget(self.acceptButton, 7, 4, 1, 1)
        self.preferencesList = QtWidgets.QListWidget(preferencesDlg)
        self.preferencesList.setMinimumSize(QtCore.QSize(150, 0))
        self.preferencesList.setMaximumSize(QtCore.QSize(150, 16777215))
        self.preferencesList.setObjectName("preferencesList")
        item = QtWidgets.QListWidgetItem()
        self.preferencesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.preferencesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.preferencesList.addItem(item)
        self.gridLayout.addWidget(self.preferencesList, 0, 1, 8, 1)
        self.closeButton = QtWidgets.QPushButton(preferencesDlg)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 7, 3, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(preferencesDlg)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.autosaveDatabase = QtWidgets.QCheckBox(self.groupBox)
        self.autosaveDatabase.setChecked(True)
        self.autosaveDatabase.setObjectName("autosaveDatabase")
        self.gridLayout_2.addWidget(self.autosaveDatabase, 3, 0, 1, 1)
        self.resetCurrentDirectoryButton = QtWidgets.QPushButton(self.groupBox)
        self.resetCurrentDirectoryButton.setObjectName("resetCurrentDirectoryButton")
        self.gridLayout_2.addWidget(self.resetCurrentDirectoryButton, 3, 1, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.groupBox)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout_2.addWidget(self.browseButton, 2, 1, 1, 1)
        self.currentPathEntry = QtWidgets.QLineEdit(self.groupBox)
        self.currentPathEntry.setReadOnly(True)
        self.currentPathEntry.setObjectName("currentPathEntry")
        self.gridLayout_2.addWidget(self.currentPathEntry, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.showCompletedTasks = QtWidgets.QCheckBox(self.page)
        self.showCompletedTasks.setObjectName("showCompletedTasks")
        self.gridLayout_3.addWidget(self.showCompletedTasks, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 551, 743))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.useFgColors = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.useFgColors.setMinimumSize(QtCore.QSize(0, 178))
        self.useFgColors.setMaximumSize(QtCore.QSize(16777215, 178))
        self.useFgColors.setCheckable(True)
        self.useFgColors.setObjectName("useFgColors")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.useFgColors)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_8 = QtWidgets.QLabel(self.useFgColors)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 0, 1, 1)
        self.fgRedNumber1 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgRedNumber1.setPrefix("")
        self.fgRedNumber1.setMaximum(255)
        self.fgRedNumber1.setObjectName("fgRedNumber1")
        self.gridLayout_9.addWidget(self.fgRedNumber1, 0, 1, 1, 1)
        self.fgGreenNumber1 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgGreenNumber1.setMaximum(255)
        self.fgGreenNumber1.setObjectName("fgGreenNumber1")
        self.gridLayout_9.addWidget(self.fgGreenNumber1, 0, 2, 1, 1)
        self.fgBlueNumber1 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgBlueNumber1.setMaximum(255)
        self.fgBlueNumber1.setObjectName("fgBlueNumber1")
        self.gridLayout_9.addWidget(self.fgBlueNumber1, 0, 3, 1, 1)
        self.fgColorLabel1 = QtWidgets.QLabel(self.useFgColors)
        self.fgColorLabel1.setMinimumSize(QtCore.QSize(30, 0))
        self.fgColorLabel1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.fgColorLabel1.setText("")
        self.fgColorLabel1.setObjectName("fgColorLabel1")
        self.gridLayout_9.addWidget(self.fgColorLabel1, 0, 4, 1, 1)
        self.changeButton6 = QtWidgets.QPushButton(self.useFgColors)
        self.changeButton6.setObjectName("changeButton6")
        self.gridLayout_9.addWidget(self.changeButton6, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.useFgColors)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 1, 0, 1, 1)
        self.fgRedNumber2 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgRedNumber2.setMaximum(255)
        self.fgRedNumber2.setObjectName("fgRedNumber2")
        self.gridLayout_9.addWidget(self.fgRedNumber2, 1, 1, 1, 1)
        self.fgGreenNumber2 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgGreenNumber2.setMaximum(255)
        self.fgGreenNumber2.setObjectName("fgGreenNumber2")
        self.gridLayout_9.addWidget(self.fgGreenNumber2, 1, 2, 1, 1)
        self.fgBlueNumber2 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgBlueNumber2.setMaximum(255)
        self.fgBlueNumber2.setObjectName("fgBlueNumber2")
        self.gridLayout_9.addWidget(self.fgBlueNumber2, 1, 3, 1, 1)
        self.fgColorLabel2 = QtWidgets.QLabel(self.useFgColors)
        self.fgColorLabel2.setText("")
        self.fgColorLabel2.setObjectName("fgColorLabel2")
        self.gridLayout_9.addWidget(self.fgColorLabel2, 1, 4, 1, 1)
        self.changeButton7 = QtWidgets.QPushButton(self.useFgColors)
        self.changeButton7.setObjectName("changeButton7")
        self.gridLayout_9.addWidget(self.changeButton7, 1, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.useFgColors)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 2, 0, 1, 1)
        self.fgRedNumber3 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgRedNumber3.setMaximum(255)
        self.fgRedNumber3.setObjectName("fgRedNumber3")
        self.gridLayout_9.addWidget(self.fgRedNumber3, 2, 1, 1, 1)
        self.fgGreenNumber3 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgGreenNumber3.setMaximum(255)
        self.fgGreenNumber3.setObjectName("fgGreenNumber3")
        self.gridLayout_9.addWidget(self.fgGreenNumber3, 2, 2, 1, 1)
        self.fgBlueNumber3 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgBlueNumber3.setMaximum(255)
        self.fgBlueNumber3.setObjectName("fgBlueNumber3")
        self.gridLayout_9.addWidget(self.fgBlueNumber3, 2, 3, 1, 1)
        self.fgColorLabel3 = QtWidgets.QLabel(self.useFgColors)
        self.fgColorLabel3.setText("")
        self.fgColorLabel3.setObjectName("fgColorLabel3")
        self.gridLayout_9.addWidget(self.fgColorLabel3, 2, 4, 1, 1)
        self.changeButton8 = QtWidgets.QPushButton(self.useFgColors)
        self.changeButton8.setObjectName("changeButton8")
        self.gridLayout_9.addWidget(self.changeButton8, 2, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.useFgColors)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 3, 0, 1, 1)
        self.fgRedNumber4 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgRedNumber4.setMaximum(255)
        self.fgRedNumber4.setObjectName("fgRedNumber4")
        self.gridLayout_9.addWidget(self.fgRedNumber4, 3, 1, 1, 1)
        self.fgGreenNumber4 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgGreenNumber4.setMaximum(255)
        self.fgGreenNumber4.setObjectName("fgGreenNumber4")
        self.gridLayout_9.addWidget(self.fgGreenNumber4, 3, 2, 1, 1)
        self.fgBlueNumber4 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgBlueNumber4.setMaximum(255)
        self.fgBlueNumber4.setObjectName("fgBlueNumber4")
        self.gridLayout_9.addWidget(self.fgBlueNumber4, 3, 3, 1, 1)
        self.fgColorLabel4 = QtWidgets.QLabel(self.useFgColors)
        self.fgColorLabel4.setText("")
        self.fgColorLabel4.setObjectName("fgColorLabel4")
        self.gridLayout_9.addWidget(self.fgColorLabel4, 3, 4, 1, 1)
        self.changeButton9 = QtWidgets.QPushButton(self.useFgColors)
        self.changeButton9.setObjectName("changeButton9")
        self.gridLayout_9.addWidget(self.changeButton9, 3, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.useFgColors)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 4, 0, 1, 1)
        self.fgRedNumber5 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgRedNumber5.setMaximum(255)
        self.fgRedNumber5.setObjectName("fgRedNumber5")
        self.gridLayout_9.addWidget(self.fgRedNumber5, 4, 1, 1, 1)
        self.fgGreenNumber5 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgGreenNumber5.setMaximum(255)
        self.fgGreenNumber5.setObjectName("fgGreenNumber5")
        self.gridLayout_9.addWidget(self.fgGreenNumber5, 4, 2, 1, 1)
        self.fgBlueNumber5 = QtWidgets.QSpinBox(self.useFgColors)
        self.fgBlueNumber5.setMaximum(255)
        self.fgBlueNumber5.setObjectName("fgBlueNumber5")
        self.gridLayout_9.addWidget(self.fgBlueNumber5, 4, 3, 1, 1)
        self.fgColorLabel5 = QtWidgets.QLabel(self.useFgColors)
        self.fgColorLabel5.setText("")
        self.fgColorLabel5.setObjectName("fgColorLabel5")
        self.gridLayout_9.addWidget(self.fgColorLabel5, 4, 4, 1, 1)
        self.changeButton10 = QtWidgets.QPushButton(self.useFgColors)
        self.changeButton10.setObjectName("changeButton10")
        self.gridLayout_9.addWidget(self.changeButton10, 4, 5, 1, 1)
        self.gridLayout_7.addWidget(self.useFgColors, 2, 0, 1, 1)
        self.useBgColors = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.useBgColors.setMinimumSize(QtCore.QSize(0, 178))
        self.useBgColors.setMaximumSize(QtCore.QSize(16777215, 178))
        self.useBgColors.setCheckable(True)
        self.useBgColors.setObjectName("useBgColors")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.useBgColors)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.bgBlueNumber5 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgBlueNumber5.setMaximum(255)
        self.bgBlueNumber5.setObjectName("bgBlueNumber5")
        self.gridLayout_8.addWidget(self.bgBlueNumber5, 4, 3, 1, 1)
        self.bgColorLabel3 = QtWidgets.QLabel(self.useBgColors)
        self.bgColorLabel3.setText("")
        self.bgColorLabel3.setObjectName("bgColorLabel3")
        self.gridLayout_8.addWidget(self.bgColorLabel3, 2, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.useBgColors)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 2, 0, 1, 1)
        self.bgGreenNumber2 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgGreenNumber2.setMaximum(255)
        self.bgGreenNumber2.setObjectName("bgGreenNumber2")
        self.gridLayout_8.addWidget(self.bgGreenNumber2, 1, 2, 1, 1)
        self.bgRedNumber1 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgRedNumber1.setPrefix("")
        self.bgRedNumber1.setMaximum(255)
        self.bgRedNumber1.setObjectName("bgRedNumber1")
        self.gridLayout_8.addWidget(self.bgRedNumber1, 0, 1, 1, 1)
        self.bgColorLabel1 = QtWidgets.QLabel(self.useBgColors)
        self.bgColorLabel1.setMinimumSize(QtCore.QSize(30, 0))
        self.bgColorLabel1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bgColorLabel1.setText("")
        self.bgColorLabel1.setObjectName("bgColorLabel1")
        self.gridLayout_8.addWidget(self.bgColorLabel1, 0, 4, 1, 1)
        self.bgRedNumber3 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgRedNumber3.setMaximum(255)
        self.bgRedNumber3.setObjectName("bgRedNumber3")
        self.gridLayout_8.addWidget(self.bgRedNumber3, 2, 1, 1, 1)
        self.bgGreenNumber3 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgGreenNumber3.setMaximum(255)
        self.bgGreenNumber3.setObjectName("bgGreenNumber3")
        self.gridLayout_8.addWidget(self.bgGreenNumber3, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.useBgColors)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.useBgColors)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.useBgColors)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 1, 0, 1, 1)
        self.bgGreenNumber5 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgGreenNumber5.setMaximum(255)
        self.bgGreenNumber5.setObjectName("bgGreenNumber5")
        self.gridLayout_8.addWidget(self.bgGreenNumber5, 4, 2, 1, 1)
        self.bgColorLabel5 = QtWidgets.QLabel(self.useBgColors)
        self.bgColorLabel5.setText("")
        self.bgColorLabel5.setObjectName("bgColorLabel5")
        self.gridLayout_8.addWidget(self.bgColorLabel5, 4, 4, 1, 1)
        self.bgColorLabel4 = QtWidgets.QLabel(self.useBgColors)
        self.bgColorLabel4.setText("")
        self.bgColorLabel4.setObjectName("bgColorLabel4")
        self.gridLayout_8.addWidget(self.bgColorLabel4, 3, 4, 1, 1)
        self.changeButton3 = QtWidgets.QPushButton(self.useBgColors)
        self.changeButton3.setObjectName("changeButton3")
        self.gridLayout_8.addWidget(self.changeButton3, 2, 5, 1, 1)
        self.bgRedNumber4 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgRedNumber4.setMaximum(255)
        self.bgRedNumber4.setObjectName("bgRedNumber4")
        self.gridLayout_8.addWidget(self.bgRedNumber4, 3, 1, 1, 1)
        self.bgRedNumber2 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgRedNumber2.setMaximum(255)
        self.bgRedNumber2.setObjectName("bgRedNumber2")
        self.gridLayout_8.addWidget(self.bgRedNumber2, 1, 1, 1, 1)
        self.bgGreenNumber4 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgGreenNumber4.setMaximum(255)
        self.bgGreenNumber4.setObjectName("bgGreenNumber4")
        self.gridLayout_8.addWidget(self.bgGreenNumber4, 3, 2, 1, 1)
        self.bgBlueNumber1 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgBlueNumber1.setMaximum(255)
        self.bgBlueNumber1.setObjectName("bgBlueNumber1")
        self.gridLayout_8.addWidget(self.bgBlueNumber1, 0, 3, 1, 1)
        self.bgBlueNumber3 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgBlueNumber3.setMaximum(255)
        self.bgBlueNumber3.setObjectName("bgBlueNumber3")
        self.gridLayout_8.addWidget(self.bgBlueNumber3, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.useBgColors)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 3, 0, 1, 1)
        self.bgBlueNumber2 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgBlueNumber2.setMaximum(255)
        self.bgBlueNumber2.setObjectName("bgBlueNumber2")
        self.gridLayout_8.addWidget(self.bgBlueNumber2, 1, 3, 1, 1)
        self.changeButton5 = QtWidgets.QPushButton(self.useBgColors)
        self.changeButton5.setObjectName("changeButton5")
        self.gridLayout_8.addWidget(self.changeButton5, 4, 5, 1, 1)
        self.changeButton2 = QtWidgets.QPushButton(self.useBgColors)
        self.changeButton2.setObjectName("changeButton2")
        self.gridLayout_8.addWidget(self.changeButton2, 1, 5, 1, 1)
        self.bgColorLabel2 = QtWidgets.QLabel(self.useBgColors)
        self.bgColorLabel2.setText("")
        self.bgColorLabel2.setObjectName("bgColorLabel2")
        self.gridLayout_8.addWidget(self.bgColorLabel2, 1, 4, 1, 1)
        self.bgRedNumber5 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgRedNumber5.setMaximum(255)
        self.bgRedNumber5.setObjectName("bgRedNumber5")
        self.gridLayout_8.addWidget(self.bgRedNumber5, 4, 1, 1, 1)
        self.bgGreenNumber1 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgGreenNumber1.setMaximum(255)
        self.bgGreenNumber1.setObjectName("bgGreenNumber1")
        self.gridLayout_8.addWidget(self.bgGreenNumber1, 0, 2, 1, 1)
        self.changeButton4 = QtWidgets.QPushButton(self.useBgColors)
        self.changeButton4.setObjectName("changeButton4")
        self.gridLayout_8.addWidget(self.changeButton4, 3, 5, 1, 1)
        self.bgBlueNumber4 = QtWidgets.QSpinBox(self.useBgColors)
        self.bgBlueNumber4.setMaximum(255)
        self.bgBlueNumber4.setObjectName("bgBlueNumber4")
        self.gridLayout_8.addWidget(self.bgBlueNumber4, 3, 3, 1, 1)
        self.changeButton1 = QtWidgets.QPushButton(self.useBgColors)
        self.changeButton1.setObjectName("changeButton1")
        self.gridLayout_8.addWidget(self.changeButton1, 0, 5, 1, 1)
        self.gridLayout_7.addWidget(self.useBgColors, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.showVerticalHeaders = QtWidgets.QCheckBox(self.groupBox_2)
        self.showVerticalHeaders.setObjectName("showVerticalHeaders")
        self.gridLayout_6.addWidget(self.showVerticalHeaders, 4, 0, 1, 3)
        self.tableAlternatingRowC = QtWidgets.QCheckBox(self.groupBox_2)
        self.tableAlternatingRowC.setObjectName("tableAlternatingRowC")
        self.gridLayout_6.addWidget(self.tableAlternatingRowC, 2, 0, 1, 3)
        self.showHorizontalHeaders = QtWidgets.QCheckBox(self.groupBox_2)
        self.showHorizontalHeaders.setObjectName("showHorizontalHeaders")
        self.gridLayout_6.addWidget(self.showHorizontalHeaders, 3, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 6, 0, 1, 1)
        self.showTableGrid = QtWidgets.QGroupBox(self.groupBox_2)
        self.showTableGrid.setCheckable(True)
        self.showTableGrid.setObjectName("showTableGrid")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.showTableGrid)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableGridStyle = QtWidgets.QComboBox(self.showTableGrid)
        self.tableGridStyle.setObjectName("tableGridStyle")
        self.tableGridStyle.addItem("")
        self.tableGridStyle.addItem("")
        self.tableGridStyle.addItem("")
        self.tableGridStyle.addItem("")
        self.tableGridStyle.addItem("")
        self.gridLayout_5.addWidget(self.tableGridStyle, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.showTableGrid, 1, 0, 1, 3)
        self.selectedTable = QtWidgets.QComboBox(self.groupBox_2)
        self.selectedTable.setObjectName("selectedTable")
        self.selectedTable.addItem("")
        self.selectedTable.addItem("")
        self.selectedTable.addItem("")
        self.gridLayout_6.addWidget(self.selectedTable, 0, 1, 1, 2)
        self.applyButton = QtWidgets.QPushButton(self.groupBox_2)
        self.applyButton.setObjectName("applyButton")
        self.gridLayout_6.addWidget(self.applyButton, 6, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 6, 1, 1, 1)
        self.useBoldAnalysisT = QtWidgets.QCheckBox(self.groupBox_2)
        self.useBoldAnalysisT.setObjectName("useBoldAnalysisT")
        self.gridLayout_6.addWidget(self.useBoldAnalysisT, 5, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 3, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.showY = QtWidgets.QCheckBox(self.groupBox_4)
        self.showY.setObjectName("showY")
        self.gridLayout_12.addWidget(self.showY, 1, 0, 1, 1)
        self.showX = QtWidgets.QCheckBox(self.groupBox_4)
        self.showX.setObjectName("showX")
        self.gridLayout_12.addWidget(self.showX, 0, 0, 1, 1)
        self.addTitle = QtWidgets.QGroupBox(self.groupBox_4)
        self.addTitle.setCheckable(True)
        self.addTitle.setObjectName("addTitle")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.addTitle)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_16 = QtWidgets.QLabel(self.addTitle)
        self.label_16.setObjectName("label_16")
        self.gridLayout_17.addWidget(self.label_16, 1, 0, 1, 1)
        self.cTitleRedNumber = QtWidgets.QSpinBox(self.addTitle)
        self.cTitleRedNumber.setMaximum(255)
        self.cTitleRedNumber.setObjectName("cTitleRedNumber")
        self.gridLayout_17.addWidget(self.cTitleRedNumber, 3, 1, 1, 1)
        self.chartTitle = QtWidgets.QLineEdit(self.addTitle)
        self.chartTitle.setObjectName("chartTitle")
        self.gridLayout_17.addWidget(self.chartTitle, 0, 1, 1, 5)
        self.cTitleGreenNumber = QtWidgets.QSpinBox(self.addTitle)
        self.cTitleGreenNumber.setMaximum(255)
        self.cTitleGreenNumber.setObjectName("cTitleGreenNumber")
        self.gridLayout_17.addWidget(self.cTitleGreenNumber, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.addTitle)
        self.label_17.setObjectName("label_17")
        self.gridLayout_17.addWidget(self.label_17, 2, 0, 1, 1)
        self.cTitleColorLabel = QtWidgets.QLabel(self.addTitle)
        self.cTitleColorLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.cTitleColorLabel.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cTitleColorLabel.setText("")
        self.cTitleColorLabel.setObjectName("cTitleColorLabel")
        self.gridLayout_17.addWidget(self.cTitleColorLabel, 3, 4, 1, 1)
        self.changeCTitleColor = QtWidgets.QPushButton(self.addTitle)
        self.changeCTitleColor.setObjectName("changeCTitleColor")
        self.gridLayout_17.addWidget(self.changeCTitleColor, 3, 5, 1, 1)
        self.chartTitleFont = QtWidgets.QFontComboBox(self.addTitle)
        self.chartTitleFont.setObjectName("chartTitleFont")
        self.gridLayout_17.addWidget(self.chartTitleFont, 1, 1, 1, 5)
        self.chartTitleSize = QtWidgets.QSpinBox(self.addTitle)
        self.chartTitleSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.chartTitleSize.setMinimum(10)
        self.chartTitleSize.setMaximum(250)
        self.chartTitleSize.setProperty("value", 10)
        self.chartTitleSize.setObjectName("chartTitleSize")
        self.gridLayout_17.addWidget(self.chartTitleSize, 2, 1, 1, 5)
        self.label_18 = QtWidgets.QLabel(self.addTitle)
        self.label_18.setObjectName("label_18")
        self.gridLayout_17.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.addTitle)
        self.label_19.setObjectName("label_19")
        self.gridLayout_17.addWidget(self.label_19, 0, 0, 1, 1)
        self.cTitleBlueNumber = QtWidgets.QSpinBox(self.addTitle)
        self.cTitleBlueNumber.setMaximum(255)
        self.cTitleBlueNumber.setObjectName("cTitleBlueNumber")
        self.gridLayout_17.addWidget(self.cTitleBlueNumber, 3, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.addTitle)
        self.label_15.setObjectName("label_15")
        self.gridLayout_17.addWidget(self.label_15, 4, 0, 1, 1)
        self.chartBoldFont = QtWidgets.QCheckBox(self.addTitle)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chartBoldFont.setFont(font)
        self.chartBoldFont.setObjectName("chartBoldFont")
        self.gridLayout_17.addWidget(self.chartBoldFont, 4, 1, 1, 1)
        self.chartItalicFont = QtWidgets.QCheckBox(self.addTitle)
        font = QtGui.QFont()
        font.setItalic(True)
        self.chartItalicFont.setFont(font)
        self.chartItalicFont.setObjectName("chartItalicFont")
        self.gridLayout_17.addWidget(self.chartItalicFont, 4, 2, 1, 1)
        self.gridLayout_12.addWidget(self.addTitle, 3, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.chartAnimation = QtWidgets.QComboBox(self.groupBox_5)
        self.chartAnimation.setObjectName("chartAnimation")
        self.chartAnimation.addItem("")
        self.chartAnimation.addItem("")
        self.chartAnimation.addItem("")
        self.chartAnimation.addItem("")
        self.gridLayout_13.addWidget(self.chartAnimation, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_5, 5, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.chartTheme = QtWidgets.QComboBox(self.groupBox_7)
        self.chartTheme.setObjectName("chartTheme")
        self.chartTheme.addItem("")
        self.chartTheme.addItem("")
        self.chartTheme.addItem("")
        self.chartTheme.addItem("")
        self.chartTheme.addItem("")
        self.chartTheme.addItem("")
        self.chartTheme.addItem("")
        self.chartTheme.addItem("")
        self.gridLayout_15.addWidget(self.chartTheme, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_7, 6, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.chartZoomOption = QtWidgets.QComboBox(self.groupBox_6)
        self.chartZoomOption.setObjectName("chartZoomOption")
        self.chartZoomOption.addItem("")
        self.chartZoomOption.addItem("")
        self.chartZoomOption.addItem("")
        self.chartZoomOption.addItem("")
        self.gridLayout_14.addWidget(self.chartZoomOption, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout_14.addWidget(self.label_20, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_6, 4, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gLineBlueNumber = QtWidgets.QSpinBox(self.groupBox_3)
        self.gLineBlueNumber.setMaximum(255)
        self.gLineBlueNumber.setObjectName("gLineBlueNumber")
        self.gridLayout_11.addWidget(self.gLineBlueNumber, 0, 3, 1, 1)
        self.gLineColorLabel = QtWidgets.QLabel(self.groupBox_3)
        self.gLineColorLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.gLineColorLabel.setMaximumSize(QtCore.QSize(30, 16777215))
        self.gLineColorLabel.setText("")
        self.gLineColorLabel.setObjectName("gLineColorLabel")
        self.gridLayout_11.addWidget(self.gLineColorLabel, 0, 4, 1, 1)
        self.changeGLineColor = QtWidgets.QPushButton(self.groupBox_3)
        self.changeGLineColor.setObjectName("changeGLineColor")
        self.gridLayout_11.addWidget(self.changeGLineColor, 0, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 1, 0, 1, 1)
        self.gLineGreenNumber = QtWidgets.QSpinBox(self.groupBox_3)
        self.gLineGreenNumber.setMaximum(255)
        self.gLineGreenNumber.setObjectName("gLineGreenNumber")
        self.gridLayout_11.addWidget(self.gLineGreenNumber, 0, 2, 1, 1)
        self.gLineRedNumber = QtWidgets.QSpinBox(self.groupBox_3)
        self.gLineRedNumber.setPrefix("")
        self.gLineRedNumber.setMaximum(255)
        self.gLineRedNumber.setObjectName("gLineRedNumber")
        self.gridLayout_11.addWidget(self.gLineRedNumber, 0, 1, 1, 1)
        self.gLineWidth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.gLineWidth.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.gLineWidth.setDecimals(1)
        self.gLineWidth.setSingleStep(0.1)
        self.gLineWidth.setProperty("value", 0.1)
        self.gLineWidth.setObjectName("gLineWidth")
        self.gridLayout_11.addWidget(self.gLineWidth, 1, 1, 1, 5)
        self.gridLayout_10.addWidget(self.groupBox_3, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem5, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget, 1, 2, 1, 3)

        self.retranslateUi(preferencesDlg)
        self.stackedWidget.setCurrentIndex(1)
        self.closeButton.clicked.connect(preferencesDlg.reject)
        self.preferencesList.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(preferencesDlg)

    def retranslateUi(self, preferencesDlg):
        _translate = QtCore.QCoreApplication.translate
        preferencesDlg.setWindowTitle(_translate("preferencesDlg", "Preferences"))
        self.acceptButton.setText(_translate("preferencesDlg", "&Accept"))
        __sortingEnabled = self.preferencesList.isSortingEnabled()
        self.preferencesList.setSortingEnabled(False)
        item = self.preferencesList.item(0)
        item.setText(_translate("preferencesDlg", "General"))
        item = self.preferencesList.item(1)
        item.setText(_translate("preferencesDlg", "Table Properties"))
        item = self.preferencesList.item(2)
        item.setText(_translate("preferencesDlg", "Graphic Chart"))
        self.preferencesList.setSortingEnabled(__sortingEnabled)
        self.closeButton.setText(_translate("preferencesDlg", "&Close"))
        self.groupBox.setTitle(_translate("preferencesDlg", "Database "))
        self.label.setText(_translate("preferencesDlg", "Current path of the database file"))
        self.autosaveDatabase.setText(_translate("preferencesDlg", "Autosave the database file"))
        self.resetCurrentDirectoryButton.setText(_translate("preferencesDlg", "&Reset"))
        self.browseButton.setText(_translate("preferencesDlg", "&Browse ..."))
        self.showCompletedTasks.setText(_translate("preferencesDlg", "Show completed tasks"))
        self.useFgColors.setTitle(_translate("preferencesDlg", "Use Foreground color for the points"))
        self.label_8.setText(_translate("preferencesDlg", "5H/Day or 1500H/Month"))
        self.fgRedNumber1.setSuffix(_translate("preferencesDlg", " Red"))
        self.fgGreenNumber1.setSuffix(_translate("preferencesDlg", " Green"))
        self.fgBlueNumber1.setSuffix(_translate("preferencesDlg", " Blue"))
        self.changeButton6.setText(_translate("preferencesDlg", "Change"))
        self.label_9.setText(_translate("preferencesDlg", "5H/Day or 1500H/Month"))
        self.fgRedNumber2.setSuffix(_translate("preferencesDlg", " Red"))
        self.fgGreenNumber2.setSuffix(_translate("preferencesDlg", " Green"))
        self.fgBlueNumber2.setSuffix(_translate("preferencesDlg", " Blue"))
        self.changeButton7.setText(_translate("preferencesDlg", "Change"))
        self.label_10.setText(_translate("preferencesDlg", "5H/Day or 1500H/Month"))
        self.fgRedNumber3.setSuffix(_translate("preferencesDlg", " Red"))
        self.fgGreenNumber3.setSuffix(_translate("preferencesDlg", " Green"))
        self.fgBlueNumber3.setSuffix(_translate("preferencesDlg", " Blue"))
        self.changeButton8.setText(_translate("preferencesDlg", "Change"))
        self.label_11.setText(_translate("preferencesDlg", "5H/Day or 1500H/Month"))
        self.fgRedNumber4.setSuffix(_translate("preferencesDlg", " Red"))
        self.fgGreenNumber4.setSuffix(_translate("preferencesDlg", " Green"))
        self.fgBlueNumber4.setSuffix(_translate("preferencesDlg", " Blue"))
        self.changeButton9.setText(_translate("preferencesDlg", "Change"))
        self.label_12.setText(_translate("preferencesDlg", "5H/Day or 1500H/Month"))
        self.fgRedNumber5.setSuffix(_translate("preferencesDlg", " Red"))
        self.fgGreenNumber5.setSuffix(_translate("preferencesDlg", " Green"))
        self.fgBlueNumber5.setSuffix(_translate("preferencesDlg", " Blue"))
        self.changeButton10.setText(_translate("preferencesDlg", "Change"))
        self.useBgColors.setTitle(_translate("preferencesDlg", "Use Background color for the points"))
        self.bgBlueNumber5.setSuffix(_translate("preferencesDlg", " Blue"))
        self.label_5.setText(_translate("preferencesDlg", "3H/Day or 90H/Month"))
        self.bgGreenNumber2.setSuffix(_translate("preferencesDlg", " Green"))
        self.bgRedNumber1.setSuffix(_translate("preferencesDlg", " Red"))
        self.bgRedNumber3.setSuffix(_translate("preferencesDlg", " Red"))
        self.bgGreenNumber3.setSuffix(_translate("preferencesDlg", " Green"))
        self.label_7.setText(_translate("preferencesDlg", "1H/Day or 30H/Month"))
        self.label_3.setText(_translate("preferencesDlg", "5H/Day or 1500H/Month"))
        self.label_4.setText(_translate("preferencesDlg", "4H/Day or 120H/Month"))
        self.bgGreenNumber5.setSuffix(_translate("preferencesDlg", " Green"))
        self.changeButton3.setText(_translate("preferencesDlg", "Change"))
        self.bgRedNumber4.setSuffix(_translate("preferencesDlg", " Red"))
        self.bgRedNumber2.setSuffix(_translate("preferencesDlg", " Red"))
        self.bgGreenNumber4.setSuffix(_translate("preferencesDlg", " Green"))
        self.bgBlueNumber1.setSuffix(_translate("preferencesDlg", " Blue"))
        self.bgBlueNumber3.setSuffix(_translate("preferencesDlg", " Blue"))
        self.label_6.setText(_translate("preferencesDlg", "2H/Day or 60H/Month"))
        self.bgBlueNumber2.setSuffix(_translate("preferencesDlg", " Blue"))
        self.changeButton5.setText(_translate("preferencesDlg", "Change"))
        self.changeButton2.setText(_translate("preferencesDlg", "Change"))
        self.bgRedNumber5.setSuffix(_translate("preferencesDlg", " Red"))
        self.bgGreenNumber1.setSuffix(_translate("preferencesDlg", " Green"))
        self.changeButton4.setText(_translate("preferencesDlg", "Change"))
        self.bgBlueNumber4.setSuffix(_translate("preferencesDlg", " Blue"))
        self.changeButton1.setText(_translate("preferencesDlg", "Change"))
        self.groupBox_2.setTitle(_translate("preferencesDlg", "Table Appearances"))
        self.label_2.setText(_translate("preferencesDlg", "Choose Table"))
        self.showVerticalHeaders.setText(_translate("preferencesDlg", "Show Vertical Headers"))
        self.tableAlternatingRowC.setText(_translate("preferencesDlg", "Set Alternating Row Colors"))
        self.showHorizontalHeaders.setText(_translate("preferencesDlg", "Show Horizontal Headers"))
        self.showTableGrid.setTitle(_translate("preferencesDlg", "Show Table\'s Grid"))
        self.tableGridStyle.setItemText(0, _translate("preferencesDlg", "SolidLine"))
        self.tableGridStyle.setItemText(1, _translate("preferencesDlg", "DashLine"))
        self.tableGridStyle.setItemText(2, _translate("preferencesDlg", "DotLine"))
        self.tableGridStyle.setItemText(3, _translate("preferencesDlg", "DashDotLine"))
        self.tableGridStyle.setItemText(4, _translate("preferencesDlg", "DashDotDotLine"))
        self.selectedTable.setItemText(0, _translate("preferencesDlg", "Table of tasks"))
        self.selectedTable.setItemText(1, _translate("preferencesDlg", "Table of completed tasks"))
        self.selectedTable.setItemText(2, _translate("preferencesDlg", "Table of analysis"))
        self.applyButton.setText(_translate("preferencesDlg", "A&pply"))
        self.useBoldAnalysisT.setText(_translate("preferencesDlg", "Use bold style on positive numbers"))
        self.groupBox_4.setTitle(_translate("preferencesDlg", "Chart Settings"))
        self.showY.setText(_translate("preferencesDlg", "Show The y Axis"))
        self.showX.setText(_translate("preferencesDlg", "Show The x Axis"))
        self.addTitle.setTitle(_translate("preferencesDlg", "Add a Title"))
        self.label_16.setText(_translate("preferencesDlg", "Font"))
        self.cTitleRedNumber.setSuffix(_translate("preferencesDlg", " Red"))
        self.cTitleGreenNumber.setSuffix(_translate("preferencesDlg", " Green"))
        self.label_17.setText(_translate("preferencesDlg", "Font Size"))
        self.changeCTitleColor.setText(_translate("preferencesDlg", "Change"))
        self.chartTitleSize.setSuffix(_translate("preferencesDlg", " pt"))
        self.label_18.setText(_translate("preferencesDlg", "Font Color"))
        self.label_19.setText(_translate("preferencesDlg", "Title"))
        self.cTitleBlueNumber.setSuffix(_translate("preferencesDlg", " Blue"))
        self.label_15.setText(_translate("preferencesDlg", "Font Style"))
        self.chartBoldFont.setText(_translate("preferencesDlg", "Bold"))
        self.chartItalicFont.setText(_translate("preferencesDlg", "Italic"))
        self.groupBox_5.setTitle(_translate("preferencesDlg", "Animation Settings"))
        self.chartAnimation.setItemText(0, _translate("preferencesDlg", "No Animation"))
        self.chartAnimation.setItemText(1, _translate("preferencesDlg", "Animate The Grid"))
        self.chartAnimation.setItemText(2, _translate("preferencesDlg", "Animate The Series"))
        self.chartAnimation.setItemText(3, _translate("preferencesDlg", "Animate All"))
        self.groupBox_7.setTitle(_translate("preferencesDlg", "Theme Settings"))
        self.chartTheme.setItemText(0, _translate("preferencesDlg", "Light Theme (Default)"))
        self.chartTheme.setItemText(1, _translate("preferencesDlg", "Cerulean Blue Theme"))
        self.chartTheme.setItemText(2, _translate("preferencesDlg", "Dark Theme"))
        self.chartTheme.setItemText(3, _translate("preferencesDlg", "Sand Brown Theme"))
        self.chartTheme.setItemText(4, _translate("preferencesDlg", "NCS Theme (Natural Color System)"))
        self.chartTheme.setItemText(5, _translate("preferencesDlg", "High Contrast Theme"))
        self.chartTheme.setItemText(6, _translate("preferencesDlg", "Icy Blue Theme"))
        self.chartTheme.setItemText(7, _translate("preferencesDlg", "Qt Theme"))
        self.groupBox_6.setTitle(_translate("preferencesDlg", "Zoom Settings"))
        self.chartZoomOption.setItemText(0, _translate("preferencesDlg", "No Zoom"))
        self.chartZoomOption.setItemText(1, _translate("preferencesDlg", "Vertical Zoom"))
        self.chartZoomOption.setItemText(2, _translate("preferencesDlg", "Horizontal Zoom"))
        self.chartZoomOption.setItemText(3, _translate("preferencesDlg", "Rectangular Zoom"))
        self.label_20.setText(_translate("preferencesDlg", "Note: You select the area with your left mouse and you unzoom it with a right click."))
        self.groupBox_3.setTitle(_translate("preferencesDlg", "Graphic Line Settings"))
        self.gLineBlueNumber.setSuffix(_translate("preferencesDlg", " Blue"))
        self.changeGLineColor.setText(_translate("preferencesDlg", "Change"))
        self.label_13.setText(_translate("preferencesDlg", "Line Color"))
        self.label_14.setText(_translate("preferencesDlg", "Line Width"))
        self.gLineGreenNumber.setSuffix(_translate("preferencesDlg", " Green"))
        self.gLineRedNumber.setSuffix(_translate("preferencesDlg", " Red"))

